import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import { UserContextProvider } from './context/userContext'
import { EventContextProvider } from './context/eventContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Polieventos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>   
        <EventContextProvider>
          <UserContextProvider>
            <Header/>
            {children}        
          </UserContextProvider>
        </EventContextProvider>     
      </body>
    </html>
  )
}
