-- CreateTable
CREATE TABLE "FACULTADES" (
    "codigo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "ubicacion" TEXT NOT NULL,
    "nro_telefono" TEXT NOT NULL,
    "id_decano" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "EMPLEADOS" (
    "identificacion" TEXT NOT NULL PRIMARY KEY,
    "nombres" TEXT NOT NULL,
    "apellidos" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "tipo_contratacion" TEXT NOT NULL,
    "tipo_empleado" TEXT NOT NULL,
    "cod_facultad" INTEGER NOT NULL,
    "codigo_sede" INTEGER NOT NULL,
    "lugar_nacimiento" INTEGER NOT NULL,
    CONSTRAINT "EMPLEADOS_cod_facultad_fkey" FOREIGN KEY ("cod_facultad") REFERENCES "FACULTADES" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "EMPLEADOS_codigo_sede_fkey" FOREIGN KEY ("codigo_sede") REFERENCES "SEDES" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "EMPLEADOS_lugar_nacimiento_fkey" FOREIGN KEY ("lugar_nacimiento") REFERENCES "CIUDADES" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "EMPLEADOS_tipo_contratacion_fkey" FOREIGN KEY ("tipo_contratacion") REFERENCES "TIPOS_CONTRATACION" ("nombre") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "EMPLEADOS_tipo_empleado_fkey" FOREIGN KEY ("tipo_empleado") REFERENCES "TIPOS_EMPLEADO" ("nombre") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "SEDES" (
    "codigo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "cod_ciudad" INTEGER NOT NULL,
    CONSTRAINT "SEDES_cod_ciudad_fkey" FOREIGN KEY ("cod_ciudad") REFERENCES "CIUDADES" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CIUDADES" (
    "codigo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "cod_dpto" INTEGER NOT NULL,
    CONSTRAINT "CIUDADES_cod_dpto_fkey" FOREIGN KEY ("cod_dpto") REFERENCES "DEPARTAMENTOS" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "DEPARTAMENTOS" (
    "codigo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "cod_pais" INTEGER NOT NULL,
    CONSTRAINT "DEPARTAMENTOS_cod_pais_fkey" FOREIGN KEY ("cod_pais") REFERENCES "PAISES" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAISES" (
    "codigo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "AREAS" (
    "codigo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "FACULTADES_codigo" INTEGER NOT NULL,
    "id_coordinador" TEXT NOT NULL,
    CONSTRAINT "AREAS_FACULTADES_codigo_fkey" FOREIGN KEY ("FACULTADES_codigo") REFERENCES "FACULTADES" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "AREAS_id_coordinador_fkey" FOREIGN KEY ("id_coordinador") REFERENCES "EMPLEADOS" ("identificacion") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PROGRAMAS" (
    "codigo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "AREAS_codigo" INTEGER NOT NULL,
    CONSTRAINT "PROGRAMAS_AREAS_codigo_fkey" FOREIGN KEY ("AREAS_codigo") REFERENCES "AREAS" ("codigo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TIPOS_EMPLEADO" (
    "nombre" TEXT NOT NULL PRIMARY KEY
);

-- CreateTable
CREATE TABLE "TIPOS_CONTRATACION" (
    "nombre" TEXT NOT NULL PRIMARY KEY
);
